package com.grash.service;

import com.grash.dto.IntervalStatusDTO;
import com.grash.model.MaintenanceInterval;
import com.grash.model.Meter;
import com.grash.model.PreventiveMaintenance;
import com.grash.model.Reading;
import com.grash.model.enums.IntervalBasis;
import com.grash.model.enums.TriggerMode;
import com.grash.repository.MaintenanceIntervalRepository;
import com.grash.repository.PreventiveMaintenanceRepository;
import com.grash.repository.ReadingRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Multi-counter maintenance intervals — "every 500 hours or 3 months,
 * whichever comes first".
 * <p>
 * Progress is computed rather than stored, so it is always right the moment a
 * reading lands. The warning threshold on each interval is what produces the
 * "due in ~30 h" line on the dossier instead of a binary overdue flag that
 * arrives too late to plan around.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class MaintenanceIntervalService {

    private static final double MILLIS_PER_DAY = 1000d * 60 * 60 * 24;
    private static final double DAYS_PER_MONTH = 30.4375;

    private final MaintenanceIntervalRepository maintenanceIntervalRepository;
    private final ReadingRepository readingRepository;
    private final PreventiveMaintenanceRepository preventiveMaintenanceRepository;

    private ScheduleService scheduleService;

    @Autowired
    public void setDeps(@Lazy ScheduleService scheduleService) {
        this.scheduleService = scheduleService;
    }

    public List<MaintenanceInterval> findByPreventiveMaintenance(Long pmId) {
        return maintenanceIntervalRepository.findByPreventiveMaintenance_Id(pmId);
    }

    public Optional<MaintenanceInterval> findById(Long id) {
        return maintenanceIntervalRepository.findById(id);
    }

    /**
     * Save an interval. The first interval on a PM makes it interval-driven, so
     * its calendar schedule — "every 1 day" unless someone set it — is retired
     * here rather than left to fire alongside the counters.
     */
    public MaintenanceInterval save(MaintenanceInterval interval) {
        MaintenanceInterval saved = maintenanceIntervalRepository.save(interval);
        if (saved.getPreventiveMaintenance() != null && saved.getPreventiveMaintenance().getId() != null) {
            preventiveMaintenanceRepository.findById(saved.getPreventiveMaintenance().getId())
                    .ifPresent(pm -> scheduleService.retireForIntervals(pm.getSchedule()));
        }
        return saved;
    }

    public void delete(Long id) {
        maintenanceIntervalRepository.deleteById(id);
    }

    public List<MaintenanceInterval> findByCompany(Long companyId) {
        return maintenanceIntervalRepository.findByCompany_Id(companyId);
    }

    /**
     * A PM with at least one interval is generated by its counters, never by
     * its calendar {@code Schedule}.
     */
    public boolean isIntervalDriven(Long preventiveMaintenanceId) {
        return preventiveMaintenanceId != null
                && !maintenanceIntervalRepository.findByPreventiveMaintenance_Id(preventiveMaintenanceId).isEmpty();
    }

    /**
     * Record that the maintenance was done, resetting every counter on it.
     */
    @Transactional
    public void markCompleted(Long preventiveMaintenanceId, Date completedAt) {
        Date when = completedAt == null ? new Date() : completedAt;
        for (MaintenanceInterval interval : findByPreventiveMaintenance(preventiveMaintenanceId)) {
            interval.setLastCompletedAt(when);
            if (interval.getBasis() == IntervalBasis.METER && interval.getMeter() != null) {
                latestReading(interval.getMeter().getId())
                        .ifPresent(interval::setLastCompletedValue);
            }
            maintenanceIntervalRepository.save(interval);
        }
    }

    /**
     * Record the completion of a work order generated from this PM.
     * <p>
     * Idempotent on the completion time: saving the same completed work order
     * again must not reset the counters to wherever the meter has got to since,
     * so a completion only counts when it is newer than what the intervals
     * already hold.
     *
     * @return whether the counters were reset
     */
    @Transactional
    public boolean recordCompletion(Long preventiveMaintenanceId, Date completedAt) {
        if (preventiveMaintenanceId == null || completedAt == null) {
            return false;
        }
        List<MaintenanceInterval> intervals = findByPreventiveMaintenance(preventiveMaintenanceId);
        boolean newer = intervals.stream().anyMatch(interval -> {
            Date since = interval.getLastCompletedAt() != null
                    ? interval.getLastCompletedAt() : interval.getCreatedAt();
            return since == null || completedAt.after(since);
        });
        if (!newer) {
            return false;
        }
        markCompleted(preventiveMaintenanceId, completedAt);
        return true;
    }

    /**
     * How far through each of a PM's counters we are, and what that means for
     * the PM as a whole under its trigger mode.
     */
    public IntervalStatusDTO status(PreventiveMaintenance pm) {
        List<MaintenanceInterval> intervals = findByPreventiveMaintenance(pm.getId());
        IntervalStatusDTO status = new IntervalStatusDTO();
        status.setPreventiveMaintenanceId(pm.getId());
        status.setTitle(pm.getName() != null ? pm.getName() : pm.getTitle());
        status.setTriggerMode(pm.getTriggerMode() == null
                ? TriggerMode.WHICHEVER_FIRST.name() : pm.getTriggerMode().name());

        if (intervals.isEmpty()) {
            // No multi-counter intervals: this PM still runs off its calendar Schedule.
            status.setCounters(Collections.emptyList());
            return status;
        }

        List<IntervalStatusDTO.CounterStatus> counters = intervals.stream()
                .map(this::counterStatus)
                .collect(Collectors.toList());
        status.setCounters(counters);

        List<IntervalStatusDTO.CounterStatus> withProgress = counters.stream()
                .filter(c -> c.getPercent() != null)
                .collect(Collectors.toList());
        if (withProgress.isEmpty()) {
            return status;
        }

        TriggerMode mode = pm.getTriggerMode() == null ? TriggerMode.WHICHEVER_FIRST : pm.getTriggerMode();
        double overall = mode == TriggerMode.WHICHEVER_FIRST
                // First counter to reach 100 % fires the PM, so the PM is as far
                // along as its furthest-along counter.
                ? withProgress.stream().mapToDouble(IntervalStatusDTO.CounterStatus::getPercent).max().orElse(0)
                : withProgress.stream().mapToDouble(IntervalStatusDTO.CounterStatus::getPercent).min().orElse(0);
        status.setPercent(overall);
        status.setDue(overall >= 100);

        IntervalStatusDTO.CounterStatus driver = withProgress.stream()
                .max(Comparator.comparingDouble(IntervalStatusDTO.CounterStatus::getPercent))
                .orElse(null);
        if (driver != null) {
            status.setDrivingCounter(driver.getLabel());
            status.setRemaining(driver.getRemaining());
            status.setRemainingUnit(driver.getUnit());
            status.setWarning(overall >= nz(driver.getWarnAtPercent(), 90.0));
        }
        return status;
    }

    private IntervalStatusDTO.CounterStatus counterStatus(MaintenanceInterval interval) {
        IntervalStatusDTO.CounterStatus counter = new IntervalStatusDTO.CounterStatus();
        counter.setIntervalId(interval.getId());
        counter.setBasis(interval.getBasis() == null ? null : interval.getBasis().name());
        counter.setIntervalValue(interval.getIntervalValue());
        counter.setIntervalUnit(interval.getUnit());
        counter.setUnit(interval.getUnit());
        counter.setWarnAtPercent(interval.getWarnAtPercent());

        if (interval.getIntervalValue() == null || interval.getIntervalValue() <= 0) {
            return counter;
        }

        if (interval.getBasis() == IntervalBasis.METER && interval.getMeter() != null) {
            Meter meter = interval.getMeter();
            counter.setLabel(meter.getName());
            if (counter.getUnit() == null) counter.setUnit(meter.getUnit());
            if (counter.getIntervalUnit() == null) counter.setIntervalUnit(meter.getUnit());
            List<Reading> readings = chronological(meter.getId());
            Optional<Double> baseline = meterBaseline(interval, readings);
            if (baseline.isEmpty()) {
                // Nothing to count from yet: the interval has not started, which
                // is 0 %, not "overdue since the machine was built".
                counter.setElapsed(0d);
                counter.setPercent(0d);
                counter.setRemaining(interval.getIntervalValue());
                return counter;
            }
            double current = readings.get(readings.size() - 1).getValue();
            double elapsed = Math.max(0, current - baseline.get());
            counter.setElapsed(elapsed);
            counter.setPercent(100.0 * elapsed / interval.getIntervalValue());
            counter.setRemaining(Math.max(0, interval.getIntervalValue() - elapsed));
            return counter;
        }

        if (interval.getBasis() == IntervalBasis.CALENDAR) {
            counter.setLabel(describeCalendar(interval));
            // Never completed: the count runs from when the interval was set up.
            Date since = interval.getLastCompletedAt() != null
                    ? interval.getLastCompletedAt() : interval.getCreatedAt();
            if (since == null) {
                return counter;
            }
            double daysElapsed = Math.max(0, (System.currentTimeMillis() - since.getTime()) / MILLIS_PER_DAY);
            double intervalDays = toDays(interval.getIntervalValue(), interval.getUnit());
            counter.setElapsed(daysElapsed);
            counter.setUnit("days");
            counter.setPercent(100.0 * daysElapsed / intervalDays);
            counter.setRemaining(Math.max(0, intervalDays - daysElapsed));
            return counter;
        }

        // EVENT intervals are driven by something happening, so there is no
        // meaningful progress to report between occurrences.
        counter.setLabel(interval.getDescription());
        return counter;
    }

    /**
     * The meter value the current cycle of a METER interval counts from.
     * <p>
     * A stored completion value is used as it is. Without one — never completed,
     * or the 0 a pack writes when it creates a meter that has no readings yet —
     * the baseline is the meter's value when the interval was set up: the last
     * reading at or before then, or failing that the first reading after. A
     * machine commissioned at 11,840 h is not 5,920 % through its 200-hour
     * greasing; it has just started counting. The derived baseline is persisted
     * so it stays put as later readings arrive. Empty when the meter has no
     * readings at all, which means the interval has not started.
     *
     * @param readings the meter's readings, oldest first
     */
    Optional<Double> meterBaseline(MaintenanceInterval interval, List<Reading> readings) {
        Double stored = interval.getLastCompletedValue();
        if (stored != null && stored != 0d) {
            return Optional.of(stored);
        }
        if (readings.isEmpty()) {
            return Optional.empty();
        }
        Date reference = interval.getLastCompletedAt() != null
                ? interval.getLastCompletedAt() : interval.getCreatedAt();
        Reading base = null;
        if (reference != null) {
            for (Reading reading : readings) {
                if (reading.getCreatedAt() != null && !reading.getCreatedAt().after(reference)) {
                    base = reading;
                }
            }
            if (base == null) {
                base = readings.stream()
                        .filter(reading -> reading.getCreatedAt() != null && reading.getCreatedAt().after(reference))
                        .findFirst()
                        .orElse(null);
            }
        }
        if (base == null) {
            base = readings.get(0);
        }
        double value = base.getValue();
        if (stored == null || stored != value) {
            interval.setLastCompletedValue(value);
            try {
                maintenanceIntervalRepository.save(interval);
            } catch (Exception e) {
                log.warn("Could not persist baseline {} for interval {}: {}", value, interval.getId(),
                        e.getMessage());
            }
        }
        return Optional.of(value);
    }

    private String describeCalendar(MaintenanceInterval interval) {
        if (interval.getDescription() != null) return interval.getDescription();
        String unit = interval.getUnit() == null ? "days" : interval.getUnit();
        return "Every " + trim(interval.getIntervalValue()) + " " + unit;
    }

    private String trim(Double value) {
        if (value == null) return "?";
        return value == Math.rint(value) ? String.valueOf(value.longValue()) : String.valueOf(value);
    }

    private double toDays(double value, String unit) {
        if (unit == null) return value;
        switch (unit.toLowerCase(Locale.ROOT)) {
            case "month":
            case "months":
            case "meses":
                return value * DAYS_PER_MONTH;
            case "week":
            case "weeks":
                return value * 7;
            case "year":
            case "years":
                return value * 365;
            default:
                return value;
        }
    }

    /** A meter's readings, oldest first. */
    private List<Reading> chronological(Long meterId) {
        return readingRepository.findByMeter_Id(meterId).stream()
                .sorted(Comparator
                        .comparing(Reading::getCreatedAt, Comparator.nullsFirst(Comparator.naturalOrder()))
                        .thenComparing(Reading::getId, Comparator.nullsFirst(Comparator.naturalOrder())))
                .collect(Collectors.toList());
    }

    private Optional<Double> latestReading(Long meterId) {
        List<Reading> readings = chronological(meterId);
        return readings.isEmpty() ? Optional.empty() : Optional.of(readings.get(readings.size() - 1).getValue());
    }

    private static double nz(Double value, double fallback) {
        return value == null ? fallback : value;
    }
}
