import Constants from 'expo-constants';
import AsyncStorage from '@react-native-async-storage/async-storage';

/**
 * Written by the container at start (public/env.js, regenerated by
 * docker-entrypoint.sh), so the same image works against any API. Falls back
 * to the values baked in at build time for `npm start`.
 */
const runtimeEnv: { API_URL?: string; AGENT_URL?: string } =
  (typeof window !== 'undefined' && (window as any).__ATLAS_ENV__) || {};

const nonEmpty = (value?: string) =>
  value && value.trim() ? value.trim() : undefined;

export const googleMapsConfig = {
  apiKey: process.env.GOOGLE_KEY
};

// Default API URL: runtime env, then Expo config
const defaultApiUrl =
  nonEmpty(runtimeEnv.API_URL) ?? Constants.expoConfig?.extra?.API_URL;
export const IS_LOCALHOST = false;

// Function to get the API URL (either custom or default)
export const getApiUrl = async (): Promise<string> => {
  try {
    // Try to get custom URL from AsyncStorage
    const customUrl = await AsyncStorage.getItem('customApiUrl');

    // Use custom URL if available, otherwise use default
    const rawApiUrl = customUrl || defaultApiUrl;
    return rawApiUrl.endsWith('/') ? rawApiUrl : rawApiUrl + '/';
  } catch (error) {
    // Fallback to default URL if there's an error
    const rawApiUrl = defaultApiUrl;
    return rawApiUrl.endsWith('/') ? rawApiUrl : rawApiUrl + '/';
  }
};

/**
 * The agent, for the on-machine assistant.
 *
 * Door 2: the technician's phone is the highest-value moment in this product
 * and MCP clients are desktop applications, so mobile talks to the agent
 * directly with the user's own token.
 */
const defaultAgentUrl =
  nonEmpty(runtimeEnv.AGENT_URL) ?? Constants.expoConfig?.extra?.AGENT_URL;

export const getAgentUrl = async (): Promise<string> => {
  try {
    const customUrl = await AsyncStorage.getItem('customAgentUrl');
    const raw = customUrl || defaultAgentUrl || '';
    if (!raw) return '';
    return raw.endsWith('/') ? raw.slice(0, -1) : raw;
  } catch (error) {
    return defaultAgentUrl || '';
  }
};
